### ISSUE TITLE
Top command errors on new servers

### ISSUE THREAD

**Issue by kennnyshiwa** [aikaterna/Fixator10-Cogs#15]
```
Traceback (most recent call last):
  File "/home/kenny/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/kenny/bb/Red-DiscordBot/cogs/CogManager/cogs/leveler/leveler.py", line 438, in top
    top_user_value = 8 + len(str(sorted_list[start_index:end_index][0][1])) + 4
IndexError: list index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kenny/redenv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 892, in invoke
    await ctx.command.invoke(ctx)
  File "/home/kenny/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 824, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/kenny/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: IndexError: list index out of range
```

seems that when the bot joins a new server where no one has any registered XP the top command can error out until some form of xp is registered

**Comment by aikaterna** [comment]
I snuck the fix into cbf1ef316fcef6046796d98b18c35b81a07bcaa1
